export const ActionTypes = {
  SET_PRODUCT: 'SET_PRODUCTS',
  ADD_PRODUCT: 'ADD_PRODUCT',
  REMOVE_PRODUCT: 'REMOVE_PRODUCT',
  EDIT_PRODUCT: ' EDIT_PRODUCT',
  SET_MULTIPRODUCT: 'SET_MULTIPRODUCT',
  ADD_MULTIPRODUCT: 'ADD_MULTIPRODUCT',
  REMOVE_MULTIPRODUCT: 'REMOVE_MULTIPRODUCT',
  EDIT_MULTIPRODUCT: ' EDIT_MULTIPRODUCT'
};
